name: Docker Build and Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # NEW STEP: Convert the repository owner's name to lowercase
      - name: Set owner to lowercase
        id: string
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # We use the new lowercase variable here for the username
          username: ${{ steps.string.outputs.owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # And we use the lowercase variable again for the tag
          tags: ghcr.io/${{ steps.string.outputs.owner }}/arch-readarr-testing:latest
